version: '3'

volumes:
  playground_data:

services:
  postgres_security:
    image: postgres
    volumes:
      - playground_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: security
      POSTGRES_PASSWORD: security
    ports:
      - 5432:5432
  keycloak:
    image: wizzn/keycloak:12
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: postgres_security
      DB_DATABASE: security
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_USER: security
      DB_PASSWORD: security
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1q2w3e4r
    ports:
      - 8080:8080
    depends_on:
      - postgres_security