version: '3'

volumes:
  playground_data:
  playground_service:

services:
  postgres_security:
    image: postgres
    volumes:
      - playground_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: security
      POSTGRES_PASSWORD: security
    ports:
      - 5432:5432
  keycloak:
    image: wizzn/keycloak:12
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: postgres_security
      DB_DATABASE: security
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_USER: security
      DB_PASSWORD: security
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1q2w3e4r
    ports:
      - 8080:8080
    depends_on:
      - postgres_security
  postgres_playground:
    image: postgres
    volumes:
      - playground_service:/var/lib/postgresql/data_service
    environment:
      POSTGRES_DB: playground_service
      POSTGRES_USER: playground_service
      POSTGRES_PASSWORD: playground_service
    ports:
      - 5431:5432
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4576