server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Security%20Server
          jwk-set-uri: http://localhost:8080/auth/realms/Security%20Server/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5431/playground_service
    username: playground_service
    password: playground_service
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG
